package rio

import (
	"fmt"
	"io"
	"reflect"
	"sort"
)

// WriteColumns generates Go source declaring column-name constants for the
// given models — typo-proof, IDE-completable column references for query
// strings:
//
//	users, err := rio.From[User]().Where(UserCols.Email+" = ?", e).All(ctx, db)
//
// The generator runs on rio's own mapping plans, so the output can never
// drift from runtime behavior; there is no source parsing and no build-time
// tool chain. Wire it up with go:generate and a three-line main:
//
//	//go:generate sh -c "go run ./internal/gencols > cols_gen.go"
//
//	// internal/gencols/main.go
//	func main() {
//		if err := rio.WriteColumns(os.Stdout, "models", models.User{}, models.Post{}); err != nil {
//			log.Fatal(err)
//		}
//	}
//
// Each model yields a <Name>Table constant (the convention- or
// TableName-derived name; a WithTableNamer handle may rename it at runtime)
// and a <Name>Cols struct value with one string field per mapped column.
func WriteColumns(w io.Writer, pkgName string, models ...any) error {
	if pkgName == "" {
		return fmt.Errorf("rio: WriteColumns needs a package name")
	}
	if len(models) == 0 {
		return fmt.Errorf("rio: WriteColumns needs at least one model")
	}

	type gen struct {
		name  string
		table string
		plan  *plan
	}
	gens := make([]gen, 0, len(models))
	byName := make(map[string]string, len(models)) // struct name → full type
	for i, m := range models {
		if m == nil {
			return fmt.Errorf("rio: WriteColumns: model %d is nil; pass a model value like models.User{}", i+1)
		}
		t := reflect.TypeOf(m)
		if t.Kind() == reflect.Pointer {
			t = t.Elem()
		}
		p, err := planFor(t)
		if err != nil {
			return err
		}
		// Two models sharing a struct name (same type twice, or User from two
		// packages) would emit colliding declarations — code that cannot
		// compile. Refuse with the fix.
		if prev, dup := byName[p.structName]; dup {
			return fmt.Errorf("rio: WriteColumns: %s and %s both generate %sTable/%sCols; generate them into separate files",
				prev, t.String(), p.structName, p.structName)
		}
		byName[p.structName] = t.String()
		table := p.defaultTable
		if p.tableOverride != "" {
			table = p.tableOverride
		}
		// Shadowing resolution keeps plan field names unique (same-depth
		// duplicates are refused, deeper ones dropped), so this is defense
		// in depth for the generated struct's compilability.
		seen := make(map[string]string, len(p.fields))
		for _, f := range p.fields {
			if prev, dup := seen[f.name]; dup {
				return fmt.Errorf("rio: WriteColumns: %s has two fields named %s (columns %q and %q, via embedding); rename one or generate columns for the embedded types separately",
					p.structName, f.name, prev, f.column)
			}
			seen[f.name] = f.column
		}
		gens = append(gens, gen{name: p.structName, table: table, plan: p})
	}
	sort.Slice(gens, func(i, j int) bool { return gens[i].name < gens[j].name })

	if _, err := fmt.Fprintf(w, "// Code generated by rio.WriteColumns; DO NOT EDIT.\n\npackage %s\n", pkgName); err != nil {
		return err
	}
	for _, g := range gens {
		if _, err := fmt.Fprintf(w, "\n// %sTable is %s's table under the naming convention; a\n// rio.WithTableNamer handle may rename it at runtime.\nconst %sTable = %q\n",
			g.name, g.name, g.name, g.table); err != nil {
			return err
		}
		if _, err := fmt.Fprintf(w, "\n// %sCols names every mapped column of %s.\nvar %sCols = struct {\n", g.name, g.name, g.name); err != nil {
			return err
		}
		for _, f := range g.plan.fields {
			if _, err := fmt.Fprintf(w, "\t%s string\n", f.name); err != nil {
				return err
			}
		}
		if _, err := fmt.Fprint(w, "}{\n"); err != nil {
			return err
		}
		for _, f := range g.plan.fields {
			if _, err := fmt.Fprintf(w, "\t%s: %q,\n", f.name, f.column); err != nil {
				return err
			}
		}
		if _, err := fmt.Fprint(w, "}\n"); err != nil {
			return err
		}
	}
	return nil
}
