package integration

import (
	"context"
	"database/sql"
	"errors"
	"testing"
	"time"

	"github.com/go-rio/rio"
)

// The end-to-end suite runs against every real database the environment
// provides: SQLite always (modernc, in-memory), PostgreSQL and MySQL when
// RIO_POSTGRES_DSN / RIO_MYSQL_DSN are set (CI services, local docker).

type User struct {
	ID        int64
	Email     string
	Age       int
	Bio       *string
	Version   int64      `rio:",version"`
	DeletedAt *time.Time `rio:",softdelete"`
	CreatedAt time.Time
	UpdatedAt time.Time

	Posts rio.HasMany[Post]
}

type Post struct {
	ID     int64
	UserID int64
	Title  string

	Author rio.BelongsTo[User] `rio:",fk:user_id"`
}

type ddl struct{ users, posts string }

var dialectDDL = map[string]ddl{
	"sqlite": {
		users: `CREATE TABLE users (
			id INTEGER PRIMARY KEY AUTOINCREMENT,
			email VARCHAR(191) NOT NULL UNIQUE,
			age INTEGER NOT NULL,
			bio TEXT,
			version INTEGER NOT NULL,
			deleted_at DATETIME,
			created_at DATETIME NOT NULL,
			updated_at DATETIME NOT NULL
		)`,
		posts: `CREATE TABLE posts (
			id INTEGER PRIMARY KEY AUTOINCREMENT,
			user_id INTEGER NOT NULL REFERENCES users (id),
			title VARCHAR(255) NOT NULL
		)`,
	},
	"postgres": {
		users: `CREATE TABLE users (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email VARCHAR(191) NOT NULL UNIQUE,
			age BIGINT NOT NULL,
			bio TEXT,
			version BIGINT NOT NULL,
			deleted_at TIMESTAMPTZ,
			created_at TIMESTAMPTZ NOT NULL,
			updated_at TIMESTAMPTZ NOT NULL
		)`,
		posts: `CREATE TABLE posts (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			user_id BIGINT NOT NULL REFERENCES users (id),
			title VARCHAR(255) NOT NULL
		)`,
	},
	"mysql": {
		users: `CREATE TABLE users (
			id BIGINT AUTO_INCREMENT PRIMARY KEY,
			email VARCHAR(191) NOT NULL UNIQUE,
			age BIGINT NOT NULL,
			bio TEXT,
			version BIGINT NOT NULL,
			deleted_at DATETIME(6),
			created_at DATETIME(6) NOT NULL,
			updated_at DATETIME(6) NOT NULL
		)`,
		posts: `CREATE TABLE posts (
			id BIGINT AUTO_INCREMENT PRIMARY KEY,
			user_id BIGINT NOT NULL,
			title VARCHAR(255) NOT NULL,
			FOREIGN KEY (user_id) REFERENCES users (id)
		)`,
	},
}

func freshSchema(t *testing.T, db *rio.DB, dialect string) {
	t.Helper()
	ctx := context.Background()
	for _, stmt := range []string{"DROP TABLE IF EXISTS posts", "DROP TABLE IF EXISTS users"} {
		if _, err := rio.Exec(ctx, db, stmt); err != nil {
			t.Fatalf("drop: %v", err)
		}
	}
	d := dialectDDL[dialect]
	for _, stmt := range []string{d.users, d.posts} {
		if _, err := rio.Exec(ctx, db, stmt); err != nil {
			t.Fatalf("ddl: %v", err)
		}
	}
}

// runSuite is the full end-to-end pass every dialect must survive.
func runSuite(t *testing.T, db *rio.DB, dialect string) {
	ctx := context.Background()
	freshSchema(t, db, dialect)

	// Insert with backfill.
	u := &User{Email: "alice@example.com", Age: 30}
	if err := rio.Insert(ctx, db, u); err != nil {
		t.Fatalf("insert: %v", err)
	}
	if u.ID == 0 {
		t.Fatal("auto-increment PK must be backfilled")
	}
	if u.Version != 1 || u.CreatedAt.IsZero() {
		t.Fatalf("maintained columns: version=%d created=%v", u.Version, u.CreatedAt)
	}

	// Timestamps survive a round-trip exactly (UTC, microsecond truncation).
	got, err := rio.Find[User](ctx, db, u.ID)
	if err != nil {
		t.Fatalf("find: %v", err)
	}
	if !got.CreatedAt.Equal(u.CreatedAt) {
		t.Fatalf("created_at round-trip: wrote %v, read %v", u.CreatedAt, got.CreatedAt)
	}

	// Unique violation translates.
	dup := &User{Email: "alice@example.com", Age: 1}
	if err := rio.Insert(ctx, db, dup); !errors.Is(err, rio.ErrDuplicateKey) {
		t.Fatalf("duplicate: %v", err)
	}

	// FK violation translates.
	if err := rio.Insert(ctx, db, &Post{UserID: 999999, Title: "orphan"}); !errors.Is(err, rio.ErrForeignKeyViolated) {
		t.Fatalf("fk: %v", err)
	}

	// Optimistic locking: a stale writer loses.
	fresh, _ := rio.Find[User](ctx, db, u.ID)
	stale := *fresh
	fresh.Age = 31
	if err := rio.Update(ctx, db, fresh); err != nil {
		t.Fatalf("update: %v", err)
	}
	stale.Age = 99
	if err := rio.Update(ctx, db, &stale); !errors.Is(err, rio.ErrStaleObject) {
		t.Fatalf("stale write must lose: %v", err)
	}

	// Preloading.
	for _, title := range []string{"first", "second"} {
		if err := rio.Insert(ctx, db, &Post{UserID: u.ID, Title: title}); err != nil {
			t.Fatalf("post: %v", err)
		}
	}
	users, err := rio.From[User]().With("Posts", rio.RelOrder("id")).All(ctx, db)
	if err != nil {
		t.Fatalf("preload: %v", err)
	}
	if len(users) != 1 || len(users[0].Posts.Rows()) != 2 {
		t.Fatalf("preload rows: %+v", users)
	}
	posts, err := rio.From[Post]().With("Author").OrderBy("id").All(ctx, db)
	if err != nil || len(posts) != 2 || posts[0].Author.Row() == nil {
		t.Fatalf("belongs-to: %v %+v", err, posts)
	}

	// Transactions: inner savepoint failure, outer commit survives.
	err = db.Tx(ctx, func(tx *rio.Tx) error {
		if err := rio.Insert(ctx, tx, &Post{UserID: u.ID, Title: "kept"}); err != nil {
			return err
		}
		_ = tx.Tx(ctx, func(tx2 *rio.Tx) error {
			if err := rio.Insert(ctx, tx2, &Post{UserID: u.ID, Title: "discarded"}); err != nil {
				return err
			}
			return errors.New("roll the savepoint back")
		})
		return nil
	})
	if err != nil {
		t.Fatalf("tx: %v", err)
	}
	n, _ := rio.From[Post]().Where("title = ?", "kept").Count(ctx, db)
	if n != 1 {
		t.Fatal("outer insert must survive")
	}
	n, _ = rio.From[Post]().Where("title = ?", "discarded").Count(ctx, db)
	if n != 0 {
		t.Fatal("savepoint insert must be rolled back")
	}

	// Soft delete and restore-on-upsert.
	if err := rio.Delete(ctx, db, fresh); err != nil {
		t.Fatalf("soft delete: %v", err)
	}
	if _, err := rio.Find[User](ctx, db, u.ID); !errors.Is(err, rio.ErrNotFound) {
		t.Fatal("soft-deleted rows hide from default queries")
	}
	trashed, err := rio.From[User]().OnlyTrashed().First(ctx, db)
	if err != nil || trashed.ID != u.ID {
		t.Fatalf("OnlyTrashed: %v", err)
	}
	revived := &User{Email: "alice@example.com", Age: 42}
	if err := rio.Upsert(ctx, db, revived, rio.OnConflict("email")); err != nil {
		t.Fatalf("upsert: %v", err)
	}
	back, err := rio.Find[User](ctx, db, u.ID)
	if err != nil {
		t.Fatalf("restore-on-upsert invariant: row must be visible again: %v", err)
	}
	if back.Age != 42 {
		t.Fatalf("upsert values: %+v", back)
	}

	// Batch insert with the documented backfill contract.
	batch := []User{{Email: "b1@example.com"}, {Email: "b2@example.com"}, {Email: "b3@example.com"}}
	if err := rio.InsertAll(ctx, db, batch); err != nil {
		t.Fatalf("insert all: %v", err)
	}
	if dialect != "mysql" {
		if batch[0].ID == 0 || batch[1].ID != batch[0].ID+1 && batch[1].ID <= batch[0].ID {
			t.Fatalf("batch backfill on %s: %+v", dialect, batch)
		}
	}

	// IN expansion, set-based writes, Raw projections, compiled queries.
	ids := []int64{batch[0].ID, batch[1].ID}
	if len(ids) > 0 && ids[0] == 0 { // mysql: look them up
		found, _ := rio.From[User]().Where("email IN (?)", []string{"b1@example.com", "b2@example.com"}).All(ctx, db)
		ids = []int64{found[0].ID, found[1].ID}
	}
	n, err = rio.From[User]().Where("id IN (?)", ids).UpdateAll(ctx, db, rio.Set{"age": rio.Expr("age + 1")})
	if err != nil || n != 2 {
		t.Fatalf("update all: %v n=%d", err, n)
	}

	type emailCount struct {
		Domain string
		N      int64
	}
	stats, err := rio.Raw[emailCount](
		"SELECT 'example.com' AS domain, count(*) AS n FROM users WHERE email LIKE ?", "%example.com").All(ctx, db)
	if err != nil || len(stats) != 1 || stats[0].N < 3 {
		t.Fatalf("raw projection: %v %+v", err, stats)
	}

	adults := rio.MustCompile[User](rio.From[User]().Where("age >= ?").OrderBy("id"))
	grown, err := adults.All(ctx, db, 1)
	if err != nil || len(grown) == 0 {
		t.Fatalf("compiled: %v %d", err, len(grown))
	}
}

// runV02Suite exercises the 0.2 surface end-to-end: WhereHas, WithCount,
// RelLimit, Attach/Detach, Rows streaming, Pluck.
func runV02Suite(t *testing.T, db *rio.DB, dialect string) {
	ctx := context.Background()
	freshSchema(t, db, dialect)
	for _, ddl := range v02DDL[dialect] {
		if _, err := rio.Exec(ctx, db, ddl); err != nil {
			t.Fatalf("v0.2 ddl: %v", err)
		}
	}

	alice := &Author{Email: "alice@example.com"}
	bob := &Author{Email: "bob@example.com"}
	for _, a := range []*Author{alice, bob} {
		if err := rio.Insert(ctx, db, a); err != nil {
			t.Fatalf("insert author: %v", err)
		}
	}
	for i, title := range []string{"one", "two", "three"} {
		if err := rio.Insert(ctx, db, &Article{AuthorID: alice.ID, Title: title, Score: i}); err != nil {
			t.Fatalf("insert article: %v", err)
		}
	}

	// WhereHas / WhereHasNot.
	withArticles, err := rio.From[Author]().WhereHas("Articles", rio.RelWhere("title <> ?", "")).All(ctx, db)
	if err != nil || len(withArticles) != 1 || withArticles[0].ID != alice.ID {
		t.Fatalf("WhereHas: %v %+v", err, withArticles)
	}
	without, err := rio.From[Author]().WhereHasNot("Articles").All(ctx, db)
	if err != nil || len(without) != 1 || without[0].ID != bob.ID {
		t.Fatalf("WhereHasNot: %v %+v", err, without)
	}

	// WithCount.
	counted, err := rio.From[Author]().WithCount("Articles").OrderBy("id").All(ctx, db)
	if err != nil || counted[0].ArticlesCount != 3 || counted[1].ArticlesCount != 0 {
		t.Fatalf("WithCount: %v %+v", err, counted)
	}

	// RelLimit with deterministic order.
	limited, err := rio.From[Author]().Where("id = ?", alice.ID).
		With("Articles", rio.RelOrder("score DESC"), rio.RelLimit(2)).All(ctx, db)
	if err != nil {
		t.Fatalf("RelLimit: %v", err)
	}
	arts := limited[0].Articles.Rows()
	if len(arts) != 2 || arts[0].Score != 2 || arts[1].Score != 1 {
		t.Fatalf("RelLimit rows: %+v", arts)
	}

	// Attach / Detach over m2m.
	golang := &Topic{Name: "go"}
	dbs := &Topic{Name: "databases"}
	for _, tp := range []*Topic{golang, dbs} {
		if err := rio.Insert(ctx, db, tp); err != nil {
			t.Fatalf("insert topic: %v", err)
		}
	}
	if err := rio.Attach(ctx, db, alice, "Topics", golang.ID, dbs.ID); err != nil {
		t.Fatalf("Attach: %v", err)
	}
	if err := rio.Attach(ctx, db, alice, "Topics", golang.ID); err != nil {
		t.Fatalf("Attach must be idempotent: %v", err)
	}
	tagged, err := rio.From[Author]().With("Topics", rio.RelOrder("name")).Where("id = ?", alice.ID).All(ctx, db)
	if err != nil || len(tagged[0].Topics.Rows()) != 2 {
		t.Fatalf("attach round-trip: %v %+v", err, tagged)
	}
	if err := rio.Detach(ctx, db, alice, "Topics", dbs.ID); err != nil {
		t.Fatalf("Detach: %v", err)
	}
	n, err := rio.From[Author]().WhereHas("Topics").Count(ctx, db)
	if err != nil || n != 1 {
		t.Fatalf("post-detach WhereHas count: %v %d", err, n)
	}

	// Rows streaming with early break.
	streamed := 0
	for _, err := range rio.From[Article]().OrderBy("id").Rows(ctx, db) {
		if err != nil {
			t.Fatalf("Rows: %v", err)
		}
		streamed++
		if streamed == 2 {
			break
		}
	}
	if streamed != 2 {
		t.Fatalf("streamed %d", streamed)
	}

	// Pluck.
	titles, err := rio.Pluck[string](ctx, db, rio.From[Article]().Where("author_id = ?", alice.ID).OrderBy("score DESC"), "title")
	if err != nil || len(titles) != 3 || titles[0] != "three" {
		t.Fatalf("Pluck: %v %v", err, titles)
	}
}

type Author struct {
	ID            int64
	Email         string
	ArticlesCount int64 `rio:",countof:Articles"`

	Articles rio.HasMany[Article]
	Topics   rio.ManyToMany[Topic] `rio:",join:author_topics"`
}

type Article struct {
	ID       int64
	AuthorID int64
	Title    string
	Score    int
}

type Topic struct {
	ID   int64
	Name string
}

var v02DDL = map[string][]string{
	"sqlite": {
		`DROP TABLE IF EXISTS author_topics`, `DROP TABLE IF EXISTS topics`, `DROP TABLE IF EXISTS articles`, `DROP TABLE IF EXISTS authors`,
		`CREATE TABLE authors (id INTEGER PRIMARY KEY AUTOINCREMENT, email VARCHAR(191) NOT NULL UNIQUE)`,
		`CREATE TABLE articles (id INTEGER PRIMARY KEY AUTOINCREMENT, author_id INTEGER NOT NULL REFERENCES authors (id), title VARCHAR(255) NOT NULL, score INTEGER NOT NULL)`,
		`CREATE TABLE topics (id INTEGER PRIMARY KEY AUTOINCREMENT, name VARCHAR(191) NOT NULL UNIQUE)`,
		`CREATE TABLE author_topics (author_id INTEGER NOT NULL, topic_id INTEGER NOT NULL, PRIMARY KEY (author_id, topic_id))`,
	},
	"postgres": {
		`DROP TABLE IF EXISTS author_topics`, `DROP TABLE IF EXISTS topics`, `DROP TABLE IF EXISTS articles`, `DROP TABLE IF EXISTS authors`,
		`CREATE TABLE authors (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, email VARCHAR(191) NOT NULL UNIQUE)`,
		`CREATE TABLE articles (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, author_id BIGINT NOT NULL REFERENCES authors (id), title VARCHAR(255) NOT NULL, score BIGINT NOT NULL)`,
		`CREATE TABLE topics (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(191) NOT NULL UNIQUE)`,
		`CREATE TABLE author_topics (author_id BIGINT NOT NULL, topic_id BIGINT NOT NULL, PRIMARY KEY (author_id, topic_id))`,
	},
	"mysql": {
		`DROP TABLE IF EXISTS author_topics`, `DROP TABLE IF EXISTS topics`, `DROP TABLE IF EXISTS articles`, `DROP TABLE IF EXISTS authors`,
		"CREATE TABLE authors (id BIGINT AUTO_INCREMENT PRIMARY KEY, email VARCHAR(191) NOT NULL UNIQUE)",
		"CREATE TABLE articles (id BIGINT AUTO_INCREMENT PRIMARY KEY, author_id BIGINT NOT NULL, title VARCHAR(255) NOT NULL, score BIGINT NOT NULL, FOREIGN KEY (author_id) REFERENCES authors (id))",
		"CREATE TABLE topics (id BIGINT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(191) NOT NULL UNIQUE)",
		"CREATE TABLE author_topics (author_id BIGINT NOT NULL, topic_id BIGINT NOT NULL, PRIMARY KEY (author_id, topic_id))",
	},
}

// v0.3: SyncRelation converges the join table on the given set.
func runV03Sync(t *testing.T, db *rio.DB, dialect string) {
	ctx := context.Background()
	// Reuses the v0.2 schema; runV02Suite must have run first.
	author, err := rio.From[Author]().Where("email = ?", "alice@example.com").First(ctx, db)
	if err != nil {
		t.Fatalf("author: %v", err)
	}
	topics, err := rio.From[Topic]().OrderBy("id").All(ctx, db)
	if err != nil || len(topics) < 2 {
		t.Fatalf("topics: %v %d", err, len(topics))
	}
	if err := rio.SyncRelation(ctx, db, author, "Topics", []int64{topics[1].ID}); err != nil {
		t.Fatalf("SyncRelation: %v", err)
	}
	synced, err := rio.From[Author]().Where("id = ?", author.ID).With("Topics").All(ctx, db)
	if err != nil {
		t.Fatalf("reload: %v", err)
	}
	if got := synced[0].Topics.Rows(); len(got) != 1 || got[0].ID != topics[1].ID {
		t.Fatalf("synced set: %+v", got)
	}
	if err := rio.SyncRelation(ctx, db, author, "Topics", []int64{}); err != nil {
		t.Fatalf("SyncRelation empty: %v", err)
	}
	n, err := rio.From[Author]().WhereHas("Topics").Count(ctx, db)
	if err != nil || n != 0 {
		t.Fatalf("empty sync: %v n=%d", err, n)
	}
	_ = dialect
}

// AllDefault exercises the dialect-specific all-defaults INSERT form.
type AllDefault struct {
	ID   int64
	Note string `rio:",omitzero"`
}

// Reminder exercises sql.NullTime storage parity with time.Time.
type Reminder struct {
	ID    int64
	At    time.Time
	Maybe sql.NullTime
}

var hardeningDDL = map[string][]string{
	"sqlite": {
		`DROP TABLE IF EXISTS all_defaults`, `DROP TABLE IF EXISTS reminders`,
		"CREATE TABLE all_defaults (id INTEGER PRIMARY KEY AUTOINCREMENT, note TEXT NOT NULL DEFAULT 'dflt')",
		"CREATE TABLE reminders (id INTEGER PRIMARY KEY, at DATETIME NOT NULL, maybe DATETIME)",
	},
	"postgres": {
		`DROP TABLE IF EXISTS all_defaults`, `DROP TABLE IF EXISTS reminders`,
		"CREATE TABLE all_defaults (id BIGSERIAL PRIMARY KEY, note TEXT NOT NULL DEFAULT 'dflt')",
		"CREATE TABLE reminders (id BIGINT PRIMARY KEY, at TIMESTAMPTZ NOT NULL, maybe TIMESTAMPTZ)",
	},
	"mysql": {
		`DROP TABLE IF EXISTS all_defaults`, `DROP TABLE IF EXISTS reminders`,
		"CREATE TABLE all_defaults (id BIGINT AUTO_INCREMENT PRIMARY KEY, note VARCHAR(32) NOT NULL DEFAULT 'dflt')",
		"CREATE TABLE reminders (id BIGINT PRIMARY KEY, at DATETIME(6) NOT NULL, maybe DATETIME(6))",
	},
}

func (AllDefault) TableName() string { return "all_defaults" }

// runHardening covers the post-v0.3.0 audit fixes end-to-end on a real
// database: all-defaults INSERT, idempotent Update (MySQL's changed-rows
// counting), whitelist column order, NullTime write parity, and UpsertAll.
func runHardening(t *testing.T, db *rio.DB, dialect string) {
	ctx := context.Background()
	for _, ddl := range hardeningDDL[dialect] {
		if _, err := rio.Exec(ctx, db, ddl); err != nil {
			t.Fatalf("ddl %q: %v", ddl, err)
		}
	}

	// All-defaults insert: every column skipped, DB defaults apply.
	blank := AllDefault{}
	if err := rio.Insert(ctx, db, &blank); err != nil {
		t.Fatalf("all-defaults insert: %v", err)
	}
	got, err := rio.Find[AllDefault](ctx, db, blank.ID)
	if err != nil || got.Note != "dflt" {
		t.Fatalf("all-defaults reload: %+v %v", got, err)
	}

	// Idempotent Update on a model without UpdatedAt/version must succeed on
	// every dialect (MySQL counts changed rows, not matched rows).
	if err := rio.Update(ctx, db, got); err != nil {
		t.Fatalf("idempotent update: %v", err)
	}
	if err := rio.Update(ctx, db, &AllDefault{ID: got.ID + 999, Note: "x"}); !errors.Is(err, rio.ErrNotFound) {
		t.Fatalf("missing row must stay ErrNotFound: %v", err)
	}

	// Whitelist order: both spellings write the same columns.
	got.Note = "swapped"
	if err := rio.Update(ctx, db, got, "note"); err != nil {
		t.Fatalf("whitelist update: %v", err)
	}

	// sql.NullTime stores rio's canonical encoding: reload compares Equal
	// against the microsecond-truncated instant, same as time.Time.
	at := time.Date(2026, 7, 9, 3, 4, 5, 123456789, time.UTC)
	rem := Reminder{ID: 1, At: at, Maybe: sql.NullTime{Time: at, Valid: true}}
	if err := rio.Insert(ctx, db, &rem); err != nil {
		t.Fatalf("reminder insert: %v", err)
	}
	back, err := rio.Find[Reminder](ctx, db, 1)
	if err != nil {
		t.Fatalf("reminder reload: %v", err)
	}
	want := at.Truncate(time.Microsecond)
	if !back.At.Equal(want) {
		t.Fatalf("time.Time round-trip: %v != %v", back.At, want)
	}
	if !back.Maybe.Valid || !back.Maybe.Time.Equal(want) {
		t.Fatalf("NullTime round-trip: %+v != %v", back.Maybe, want)
	}
	if n, err := rio.From[Reminder]().Where("maybe = ?", sql.NullTime{Time: at, Valid: true}).Count(ctx, db); err != nil || n != 1 {
		t.Fatalf("NullTime arg must match stored encoding: n=%d %v", n, err)
	}

	// UpsertAll smoke: insert two, re-upsert with a change. Batch inserts
	// backfill no ids on MySQL (documented contract) — reload for them.
	if err := rio.InsertAll(ctx, db, []AllDefault{{Note: "a"}, {Note: "b"}}); err != nil {
		t.Fatalf("InsertAll: %v", err)
	}
	stored, err := rio.From[AllDefault]().Where("note IN (?)", []string{"a", "b"}).OrderBy("note").All(ctx, db)
	if err != nil || len(stored) != 2 {
		t.Fatalf("reload batch: %v %d", err, len(stored))
	}
	stored[0].Note = "a2"
	if err := rio.UpsertAll(ctx, db, stored, rio.OnConflict("id"), rio.DoUpdate("note")); err != nil {
		t.Fatalf("UpsertAll: %v", err)
	}
	re, err := rio.Find[AllDefault](ctx, db, stored[0].ID)
	if err != nil || re.Note != "a2" {
		t.Fatalf("UpsertAll effect: %+v %v", re, err)
	}

	// *time.Time CreatedAt/UpdatedAt are auto-stamped and round-trip, like the
	// value form (round-2 audit fix).
	if _, err := rio.Exec(ctx, db, "DROP TABLE IF EXISTS ptr_stampeds"); err != nil {
		t.Fatalf("ptr-stamp drop: %v", err)
	}
	if _, err := rio.Exec(ctx, db, ptrStampDDL[dialect]); err != nil {
		t.Fatalf("ptr-stamp ddl: %v", err)
	}
	ps := PtrStamped{Name: "x"}
	if err := rio.Insert(ctx, db, &ps); err != nil {
		t.Fatalf("ptr-stamp insert: %v", err)
	}
	if ps.CreatedAt == nil || ps.UpdatedAt == nil {
		t.Fatalf("*time.Time timestamps not stamped: %+v", ps)
	}
	psBack, err := rio.Find[PtrStamped](ctx, db, ps.ID)
	if err != nil {
		t.Fatalf("ptr-stamp reload: %v", err)
	}
	if psBack.CreatedAt == nil || !psBack.CreatedAt.Equal(*ps.CreatedAt) {
		t.Fatalf("*time.Time CreatedAt round-trip: %v != %v", psBack.CreatedAt, ps.CreatedAt)
	}

	// A relation keyed by a binary column ([]byte PK/FK) must preload: the
	// key binds as the original bytes, not a stringified map key that would
	// miss a BLOB/BYTEA column (round-2 audit found this silently empty).
	for _, ddl := range binKeyDDL[dialect] {
		if _, err := rio.Exec(ctx, db, ddl); err != nil {
			t.Fatalf("bin-key ddl %q: %v", ddl, err)
		}
	}
	pk := []byte{0xDE, 0xAD, 0xBE, 0xEF}
	if err := rio.Insert(ctx, db, &BinParent{ID: pk}); err != nil {
		t.Fatalf("bin parent: %v", err)
	}
	if err := rio.Insert(ctx, db, &BinChild{ID: 1, ParentID: pk, Label: "kid"}); err != nil {
		t.Fatalf("bin child: %v", err)
	}
	bps, err := rio.From[BinParent]().With("Kids").All(ctx, db)
	if err != nil {
		t.Fatalf("bin preload: %v", err)
	}
	if len(bps) != 1 || len(bps[0].Kids.Rows()) != 1 || bps[0].Kids.Rows()[0].Label != "kid" {
		t.Fatalf("[]byte-keyed preload lost children: %+v", bps)
	}

	// Codex audit #1: a savepoint whose inner context died must still roll
	// back — its ROLLBACK TO runs on a cancellation-decoupled context, so the
	// inner insert cannot silently survive into the outer commit when the
	// caller swallows the inner error.
	spRow := AllDefault{Note: "sp-leak"}
	err = db.Tx(ctx, func(tx *rio.Tx) error {
		inner, cancel := context.WithCancel(ctx)
		defer cancel()
		spErr := tx.Tx(inner, func(sp *rio.Tx) error {
			if err := rio.Insert(inner, sp, &spRow); err != nil {
				return err
			}
			cancel() // the inner unit's deadline fires between statements
			return errors.New("inner failure after its context died")
		})
		if spErr == nil {
			t.Fatal("inner savepoint must report the failure")
		}
		return nil // swallowed: the outer transaction commits
	})
	if err != nil {
		t.Fatalf("outer tx after swallowed savepoint failure: %v", err)
	}
	if spRow.ID == 0 {
		t.Fatal("inner insert must have run before the rollback")
	}
	if _, err := rio.Find[AllDefault](ctx, db, spRow.ID); !errors.Is(err, rio.ErrNotFound) {
		t.Fatalf("a row inside the rolled-back savepoint must not survive the outer commit: %v", err)
	}
}

// BinParent/BinChild verify preloading across a binary ([]byte) key.
type BinParent struct {
	ID   []byte                `rio:"id,pk,noautoincr"`
	Kids rio.HasMany[BinChild] `rio:",fk:parent_id"`
}
type BinChild struct {
	ID       int64
	ParentID []byte
	Label    string
}

var binKeyDDL = map[string][]string{
	"sqlite": {
		`DROP TABLE IF EXISTS bin_children`, `DROP TABLE IF EXISTS bin_parents`,
		"CREATE TABLE bin_parents (id BLOB PRIMARY KEY)",
		"CREATE TABLE bin_children (id INTEGER PRIMARY KEY, parent_id BLOB, label TEXT)",
	},
	"postgres": {
		`DROP TABLE IF EXISTS bin_children`, `DROP TABLE IF EXISTS bin_parents`,
		"CREATE TABLE bin_parents (id BYTEA PRIMARY KEY)",
		"CREATE TABLE bin_children (id BIGINT PRIMARY KEY, parent_id BYTEA, label TEXT)",
	},
	"mysql": {
		`DROP TABLE IF EXISTS bin_children`, `DROP TABLE IF EXISTS bin_parents`,
		"CREATE TABLE bin_parents (id VARBINARY(16) PRIMARY KEY)",
		"CREATE TABLE bin_children (id BIGINT PRIMARY KEY, parent_id VARBINARY(16), label TEXT)",
	},
}

// PtrStamped verifies *time.Time timestamps auto-stamp and round-trip.
type PtrStamped struct {
	ID        int64
	Name      string
	CreatedAt *time.Time
	UpdatedAt *time.Time
}

var ptrStampDDL = map[string]string{
	"sqlite":   "CREATE TABLE ptr_stampeds (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, created_at DATETIME, updated_at DATETIME)",
	"postgres": "CREATE TABLE ptr_stampeds (id BIGSERIAL PRIMARY KEY, name TEXT NOT NULL, created_at TIMESTAMPTZ, updated_at TIMESTAMPTZ)",
	"mysql":    "CREATE TABLE ptr_stampeds (id BIGINT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(32) NOT NULL, created_at DATETIME(6), updated_at DATETIME(6))",
}
