package integration

import (
	"context"
	"errors"
	"testing"
	"time"

	"github.com/go-rio/rio"
)

// The end-to-end suite runs against every real database the environment
// provides: SQLite always (modernc, in-memory), PostgreSQL and MySQL when
// RIO_POSTGRES_DSN / RIO_MYSQL_DSN are set (CI services, local docker).

type User struct {
	ID        int64
	Email     string
	Age       int
	Bio       *string
	Version   int64      `rio:",version"`
	DeletedAt *time.Time `rio:",softdelete"`
	CreatedAt time.Time
	UpdatedAt time.Time

	Posts rio.HasMany[Post]
}

type Post struct {
	ID     int64
	UserID int64
	Title  string

	Author rio.BelongsTo[User] `rio:",fk:user_id"`
}

type ddl struct{ users, posts string }

var dialectDDL = map[string]ddl{
	"sqlite": {
		users: `CREATE TABLE users (
			id INTEGER PRIMARY KEY AUTOINCREMENT,
			email VARCHAR(191) NOT NULL UNIQUE,
			age INTEGER NOT NULL,
			bio TEXT,
			version INTEGER NOT NULL,
			deleted_at DATETIME,
			created_at DATETIME NOT NULL,
			updated_at DATETIME NOT NULL
		)`,
		posts: `CREATE TABLE posts (
			id INTEGER PRIMARY KEY AUTOINCREMENT,
			user_id INTEGER NOT NULL REFERENCES users (id),
			title VARCHAR(255) NOT NULL
		)`,
	},
	"postgres": {
		users: `CREATE TABLE users (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email VARCHAR(191) NOT NULL UNIQUE,
			age BIGINT NOT NULL,
			bio TEXT,
			version BIGINT NOT NULL,
			deleted_at TIMESTAMPTZ,
			created_at TIMESTAMPTZ NOT NULL,
			updated_at TIMESTAMPTZ NOT NULL
		)`,
		posts: `CREATE TABLE posts (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			user_id BIGINT NOT NULL REFERENCES users (id),
			title VARCHAR(255) NOT NULL
		)`,
	},
	"mysql": {
		users: `CREATE TABLE users (
			id BIGINT AUTO_INCREMENT PRIMARY KEY,
			email VARCHAR(191) NOT NULL UNIQUE,
			age BIGINT NOT NULL,
			bio TEXT,
			version BIGINT NOT NULL,
			deleted_at DATETIME(6),
			created_at DATETIME(6) NOT NULL,
			updated_at DATETIME(6) NOT NULL
		)`,
		posts: `CREATE TABLE posts (
			id BIGINT AUTO_INCREMENT PRIMARY KEY,
			user_id BIGINT NOT NULL,
			title VARCHAR(255) NOT NULL,
			FOREIGN KEY (user_id) REFERENCES users (id)
		)`,
	},
}

func freshSchema(t *testing.T, db *rio.DB, dialect string) {
	t.Helper()
	ctx := context.Background()
	for _, stmt := range []string{"DROP TABLE IF EXISTS posts", "DROP TABLE IF EXISTS users"} {
		if _, err := rio.Exec(ctx, db, stmt); err != nil {
			t.Fatalf("drop: %v", err)
		}
	}
	d := dialectDDL[dialect]
	for _, stmt := range []string{d.users, d.posts} {
		if _, err := rio.Exec(ctx, db, stmt); err != nil {
			t.Fatalf("ddl: %v", err)
		}
	}
}

// runSuite is the full end-to-end pass every dialect must survive.
func runSuite(t *testing.T, db *rio.DB, dialect string) {
	ctx := context.Background()
	freshSchema(t, db, dialect)

	// Insert with backfill.
	u := &User{Email: "alice@example.com", Age: 30}
	if err := rio.Insert(ctx, db, u); err != nil {
		t.Fatalf("insert: %v", err)
	}
	if u.ID == 0 {
		t.Fatal("auto-increment PK must be backfilled")
	}
	if u.Version != 1 || u.CreatedAt.IsZero() {
		t.Fatalf("maintained columns: version=%d created=%v", u.Version, u.CreatedAt)
	}

	// Timestamps survive a round-trip exactly (UTC, microsecond truncation).
	got, err := rio.Find[User](ctx, db, u.ID)
	if err != nil {
		t.Fatalf("find: %v", err)
	}
	if !got.CreatedAt.Equal(u.CreatedAt) {
		t.Fatalf("created_at round-trip: wrote %v, read %v", u.CreatedAt, got.CreatedAt)
	}

	// Unique violation translates.
	dup := &User{Email: "alice@example.com", Age: 1}
	if err := rio.Insert(ctx, db, dup); !errors.Is(err, rio.ErrDuplicateKey) {
		t.Fatalf("duplicate: %v", err)
	}

	// FK violation translates.
	if err := rio.Insert(ctx, db, &Post{UserID: 999999, Title: "orphan"}); !errors.Is(err, rio.ErrForeignKeyViolated) {
		t.Fatalf("fk: %v", err)
	}

	// Optimistic locking: a stale writer loses.
	fresh, _ := rio.Find[User](ctx, db, u.ID)
	stale := *fresh
	fresh.Age = 31
	if err := rio.Update(ctx, db, fresh); err != nil {
		t.Fatalf("update: %v", err)
	}
	stale.Age = 99
	if err := rio.Update(ctx, db, &stale); !errors.Is(err, rio.ErrStaleObject) {
		t.Fatalf("stale write must lose: %v", err)
	}

	// Preloading.
	for _, title := range []string{"first", "second"} {
		if err := rio.Insert(ctx, db, &Post{UserID: u.ID, Title: title}); err != nil {
			t.Fatalf("post: %v", err)
		}
	}
	users, err := rio.From[User]().With("Posts", rio.RelOrder("id")).All(ctx, db)
	if err != nil {
		t.Fatalf("preload: %v", err)
	}
	if len(users) != 1 || len(users[0].Posts.Rows()) != 2 {
		t.Fatalf("preload rows: %+v", users)
	}
	posts, err := rio.From[Post]().With("Author").OrderBy("id").All(ctx, db)
	if err != nil || len(posts) != 2 || posts[0].Author.Row() == nil {
		t.Fatalf("belongs-to: %v %+v", err, posts)
	}

	// Transactions: inner savepoint failure, outer commit survives.
	err = db.Tx(ctx, func(tx *rio.Tx) error {
		if err := rio.Insert(ctx, tx, &Post{UserID: u.ID, Title: "kept"}); err != nil {
			return err
		}
		_ = tx.Tx(ctx, func(tx2 *rio.Tx) error {
			if err := rio.Insert(ctx, tx2, &Post{UserID: u.ID, Title: "discarded"}); err != nil {
				return err
			}
			return errors.New("roll the savepoint back")
		})
		return nil
	})
	if err != nil {
		t.Fatalf("tx: %v", err)
	}
	n, _ := rio.From[Post]().Where("title = ?", "kept").Count(ctx, db)
	if n != 1 {
		t.Fatal("outer insert must survive")
	}
	n, _ = rio.From[Post]().Where("title = ?", "discarded").Count(ctx, db)
	if n != 0 {
		t.Fatal("savepoint insert must be rolled back")
	}

	// Soft delete and restore-on-upsert.
	if err := rio.Delete(ctx, db, fresh); err != nil {
		t.Fatalf("soft delete: %v", err)
	}
	if _, err := rio.Find[User](ctx, db, u.ID); !errors.Is(err, rio.ErrNotFound) {
		t.Fatal("soft-deleted rows hide from default queries")
	}
	trashed, err := rio.From[User]().OnlyTrashed().First(ctx, db)
	if err != nil || trashed.ID != u.ID {
		t.Fatalf("OnlyTrashed: %v", err)
	}
	revived := &User{Email: "alice@example.com", Age: 42}
	if err := rio.Upsert(ctx, db, revived, rio.OnConflict("email")); err != nil {
		t.Fatalf("upsert: %v", err)
	}
	back, err := rio.Find[User](ctx, db, u.ID)
	if err != nil {
		t.Fatalf("restore-on-upsert invariant: row must be visible again: %v", err)
	}
	if back.Age != 42 {
		t.Fatalf("upsert values: %+v", back)
	}

	// Batch insert with the documented backfill contract.
	batch := []User{{Email: "b1@example.com"}, {Email: "b2@example.com"}, {Email: "b3@example.com"}}
	if err := rio.InsertAll(ctx, db, batch); err != nil {
		t.Fatalf("insert all: %v", err)
	}
	if dialect != "mysql" {
		if batch[0].ID == 0 || batch[1].ID != batch[0].ID+1 && batch[1].ID <= batch[0].ID {
			t.Fatalf("batch backfill on %s: %+v", dialect, batch)
		}
	}

	// IN expansion, set-based writes, Raw projections, compiled queries.
	ids := []int64{batch[0].ID, batch[1].ID}
	if len(ids) > 0 && ids[0] == 0 { // mysql: look them up
		found, _ := rio.From[User]().Where("email IN (?)", []string{"b1@example.com", "b2@example.com"}).All(ctx, db)
		ids = []int64{found[0].ID, found[1].ID}
	}
	n, err = rio.From[User]().Where("id IN (?)", ids).UpdateAll(ctx, db, rio.Set{"age": rio.Expr("age + 1")})
	if err != nil || n != 2 {
		t.Fatalf("update all: %v n=%d", err, n)
	}

	type emailCount struct {
		Domain string
		N      int64
	}
	stats, err := rio.Raw[emailCount](
		"SELECT 'example.com' AS domain, count(*) AS n FROM users WHERE email LIKE ?", "%example.com").All(ctx, db)
	if err != nil || len(stats) != 1 || stats[0].N < 3 {
		t.Fatalf("raw projection: %v %+v", err, stats)
	}

	adults := rio.MustCompile[User](rio.From[User]().Where("age >= ?").OrderBy("id"))
	grown, err := adults.All(ctx, db, 1)
	if err != nil || len(grown) == 0 {
		t.Fatalf("compiled: %v %d", err, len(grown))
	}
}
